In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv("/content/BankNote_Authentication.csv")

In [ ]:
df.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [ ]:
df.tail()

variance  skewness  curtosis  entropy  class
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

In [ ]:
df.isnull().sum()

variance    0
skewness    0
curtosis    0
entropy     0
class       0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   variance  1372 non-null   float64
 1   skewness  1372 non-null   float64
 2   curtosis  1372 non-null   float64
 3   entropy   1372 non-null   float64
 4   class     1372 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 53.7 KB


In [ ]:
df['class'].unique

<bound method Series.unique of 0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: class, Length: 1372, dtype: int64>

In [ ]:
df['class'].value_counts()

0    762
1    610
Name: class, dtype: int64

In [ ]:
df.shape


(1372, 5)

In [ ]:
df.columns

Index(['variance', 'skewness', 'curtosis', 'entropy', 'class'], dtype='object')

In [ ]:
df['class'].value_counts(normalize= True)*100

0    55.539359
1    44.460641
Name: class, dtype: float64

In [ ]:
x = df.drop('class', axis = 1)
y = df['class']

In [ ]:
x.shape

(1372, 4)

In [ ]:
y.shape

(1372,)

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25, random_state =42)

In [ ]:
import tensorflow as tf


In [ ]:
print(tf.__version__)

2.6.0


In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
from tensorflow.keras.layers import Dense , InputLayer , Dropout

In [ ]:
model1 = Sequential()
model1.add(Dense())
model1.add(Dense(6, input_shape = (4,),kernel_initializer='he_uniform',activation='relu'))
model1.add(Dense(1, activation='sigmoid'))


In [ ]:
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 30        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 7         
Total params: 37
Trainable params: 37
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model1.compile(optimizer="sgd",
              loss= "binary_crossentropy",
              metrics=["accuracy"])


In [ ]:
model1.get_weights()

[array([[ 0.11376858,  0.2844447 , -0.9285253 , -0.39202577,  1.0377752 ,
          0.9558414 ],
        [-0.21048868, -0.26349175, -0.3765    ,  0.26417708,  0.7142726 ,
          0.77768505],
        [-0.38974786,  0.04257214,  0.35262597, -0.76116556, -0.66913295,
         -0.5590701 ],
        [-1.222844  , -0.7915571 , -0.5834882 , -0.43480462, -0.9056198 ,
          1.1190592 ]], dtype=float32),
 array([0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[0.12637019],
        [0.8033501 ],
        [0.69473994],
        [0.68849623],
        [0.09505522],
        [0.70011854]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
model1.fit(x_train, y_train, epochs= 10)

Epoch 1/10
33/33 [==============================] - 0s 3ms/step - loss: 0.0156 - accuracy: 0.9971
Epoch 2/10
33/33 [==============================] - 0s 3ms/step - loss: 0.0154 - accuracy: 0.9971
Epoch 3/10
33/33 [==============================] - 0s 4ms/step - loss: 0.0153 - accuracy: 0.9971
Epoch 4/10
33/33 [==============================] - 0s 3ms/step - loss: 0.0151 - accuracy: 0.9971
Epoch 5/10
33/33 [==============================] - 0s 3ms/step - loss: 0.0150 - accuracy: 0.9971
Epoch 6/10
33/33 [==============================] - 0s 3ms/step - loss: 0.0148 - accuracy: 0.9971
Epoch 7/10
33/33 [==============================] - 0s 4ms/step - loss: 0.0147 - accuracy: 0.9971
Epoch 8/10
33/33 [==============================] - 0s 4ms/step - loss: 0.0146 - accuracy: 0.9971
Epoch 9/10
33/33 [==============================] - 0s 4ms/step - loss: 0.0144 - accuracy: 0.9971
Epoch 10/10
33/33 [==============================] - 0s 4ms/step - loss: 0.0143 - accuracy: 0.9971


In [ ]:
model1.evaluate(x_test,y_test)

11/11 [==============================] - 0s 3ms/step - loss: 0.0204 - accuracy: 0.9942


[0.020405635237693787, 0.9941691160202026]

In [ ]:
model1.get_weights()

[array([[ 0.08979251,  0.10492481, -1.3343153 , -0.42051968,  1.5247808 ,
          0.759129  ],
        [-0.2007038 , -0.23969066, -0.48715898, -0.1245167 ,  0.6970256 ,
          0.5678226 ],
        [-0.4971286 , -0.5994728 , -0.2678762 , -1.0898618 ,  0.50855476,
         -0.7352004 ],
        [-1.1873101 , -0.6379416 , -0.2094193 , -0.25290692, -0.95970243,
          1.125224  ]], dtype=float32),
 array([ 0.0026236 ,  0.07434568,  0.1477498 ,  0.23147283,  0.1169635 ,
        -0.00820508], dtype=float32),
 array([[ 0.13280682],
        [ 0.838293  ],
        [ 1.0795842 ],
        [ 0.98826057],
        [-1.0832465 ],
        [ 0.34086657]], dtype=float32),
 array([-0.26196373], dtype=float32)]

In [ ]:
y_predict1 = model1.predict(x_test)

In [ ]:
y_predict1.shape

(343, 1)

In [ ]:
y_pred1 = y_predict1.flatten()

In [ ]:
y_pred1.shape

(343,)

In [ ]:
a= np.arange(1,10).reshape(3,3)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a=a.flatten()
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y_pred1

array([1.39669632e-04, 3.45240057e-01, 4.27193493e-02, 2.09551854e-06,
       3.83685553e-03, 3.75958346e-03, 8.53649923e-04, 8.01300572e-04,
       6.58289855e-03, 1.13324460e-03, 9.50818837e-01, 9.97490287e-01,
       1.24449460e-02, 9.51131642e-01, 8.70028064e-02, 9.80852902e-01,
       8.77918780e-01, 8.82227957e-01, 9.98931587e-01, 8.28618824e-01,
       1.18598517e-03, 2.40610377e-03, 7.59212852e-01, 1.67643302e-03,
       9.97324824e-01, 6.06169633e-04, 2.84458802e-05, 9.53129053e-01,
       8.07027027e-05, 9.57410230e-05, 9.98763204e-01, 1.96513091e-03,
       1.18959947e-02, 9.99625921e-01, 9.98396456e-01, 1.97230722e-04,
       9.39304292e-01, 9.07768786e-01, 9.97972071e-01, 1.23613235e-03,
       1.27752975e-03, 9.97633100e-01, 9.75582540e-01, 1.68462738e-03,
       9.76010263e-01, 9.90783811e-01, 9.27261889e-01, 4.21754178e-03,
       1.41928801e-02, 9.85794306e-01, 3.82410572e-03, 6.94270071e-04,
       2.97336464e-05, 3.39907536e-04, 3.09721357e-03, 9.80491757e-01,
      

In [ ]:
y_class1 = (y_pred1>0.5).astype(int)
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix (y_test, y_class1)


array([[191,   0],
       [  2, 150]])

In [ ]:
accuracy_score (y_test, y_class1)

0.9883381924198251

In [ ]:
model21 = Sequential()
model21.add(Dense(6, input_shape = (4,),kernel_initializer='he_uniform',activation='relu'))
model21.add(Dropout(rate = 0.2))
model21.add(Dense(1, activation='sigmoid'))
model21.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 6)                 30        
_________________________________________________________________
dropout_2 (Dropout)          (None, 6)                 0         
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 7         
Total params: 37
Trainable params: 37
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model21.get_weights()

[array([[-0.86713624, -0.24375945, -0.14258838,  0.8127171 , -0.93280053,
         -0.27860284],
        [ 0.49973273,  0.45998275, -0.27298063, -0.9291843 ,  0.60820735,
         -1.1582721 ],
        [ 0.96883094,  1.1939746 , -0.50221616,  1.0621568 ,  1.1499516 ,
          0.2808988 ],
        [ 0.66136277, -0.36405867, -0.24424851,  0.48675966, -0.34779328,
         -0.8131472 ]], dtype=float32),
 array([0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.65807223],
        [ 0.59981596],
        [-0.8125039 ],
        [ 0.5673747 ],
        [-0.15682638],
        [-0.3001082 ]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
model21.compile(optimizer="sgd",
              loss= "binary_crossentropy",
              metrics=["accuracy"])
model21.fit(x_train, y_train, epochs= 10)

Epoch 1/10
33/33 [==============================] - 1s 3ms/step - loss: 0.2491 - accuracy: 0.8902
Epoch 2/10
33/33 [==============================] - 0s 3ms/step - loss: 0.2302 - accuracy: 0.9067
Epoch 3/10
33/33 [==============================] - 0s 4ms/step - loss: 0.2238 - accuracy: 0.9077
Epoch 4/10
33/33 [==============================] - 0s 3ms/step - loss: 0.2308 - accuracy: 0.9086
Epoch 5/10
33/33 [==============================] - 0s 4ms/step - loss: 0.2253 - accuracy: 0.9125
Epoch 6/10
33/33 [==============================] - 0s 4ms/step - loss: 0.2230 - accuracy: 0.9096
Epoch 7/10
33/33 [==============================] - 0s 3ms/step - loss: 0.2223 - accuracy: 0.9155
Epoch 8/10
33/33 [==============================] - 0s 3ms/step - loss: 0.2232 - accuracy: 0.9086
Epoch 9/10
33/33 [==============================] - 0s 4ms/step - loss: 0.2230 - accuracy: 0.9145
Epoch 10/10
33/33 [==============================] - 0s 3ms/step - loss: 0.2284 - accuracy: 0.9116


In [ ]:
model21.evaluate(x_test,y_test)

11/11 [==============================] - 0s 3ms/step - loss: 0.1216 - accuracy: 0.9854


[0.12158098816871643, 0.9854227304458618]

In [ ]:
y_predict21 = model21.predict(x_test)
y_pred21 = y_predict21.flatten()
y_class21 = (y_pred2>0.5).astype(int)



In [ ]:
accuracy_score (y_test, y_class21)

0.9941690962099126

In [ ]:


confusion_matrix (y_test, y_class21)


array([[191,   0],
       [  2, 150]])

In [ ]:
y_class2.shape

(343, 1)

In [ ]:
confusion_matrix (y_test, y_class2)

array([[191,   0],
       [  0, 152]])

In [ ]:
!pip3 install ann_visualizer

In [ ]:
from ann_visualizer.visualize import ann_viz
ann_viz(model1, title = "ANN")

In [ ]:
model2 = Sequential()
model2.add(Dense(64, input_shape = (4,), activation='relu'))
model2.add(Dense(32,  activation='relu'))
model2.add(Dense(16,  activation='relu'))
model2.add(Dense(8,  activation='relu'))
model2.add(Dense(1,activation='sigmoid'))

In [ ]:
ann_viz(model2, title = "ANN")

In [ ]:
model2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 64)                320       
_________________________________________________________________
dense_6 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_7 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 9         
Total params: 3,073
Trainable params: 3,073
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model2.get_weights()

[array([[-0.2308492 , -0.05377564,  0.13472632, -0.18052042, -0.25732887,
         -0.11518696,  0.23327076, -0.22173351, -0.20207873, -0.10831267,
         -0.21794423, -0.29592156, -0.12812977, -0.27063695,  0.12859988,
          0.15952352, -0.1422761 , -0.2646229 ,  0.15380466,  0.20298117,
          0.0183135 ,  0.18738836, -0.04274735, -0.22925298,  0.28236097,
          0.095422  , -0.14795409, -0.17604908,  0.25827032,  0.15207663,
          0.14467523,  0.27026492, -0.25016576, -0.25891587, -0.25649777,
         -0.20651466, -0.291832  ,  0.0580079 , -0.22294638, -0.23759156,
         -0.03989303, -0.24904126,  0.03250316, -0.15513596, -0.00801849,
          0.07405946,  0.05469701,  0.12991977,  0.0295102 ,  0.2656818 ,
         -0.2960778 , -0.18493667, -0.10564215,  0.21090692,  0.1789839 ,
          0.17390576,  0.16718599,  0.25770795, -0.1572853 , -0.04793802,
         -0.16638733, -0.06178994,  0.26316196, -0.27505645],
        [-0.26643983, -0.04817505, -0.0496686 , -0

In [ ]:
model2.compile(optimizer="adam",
              loss= "binary_crossentropy",
              metrics=["accuracy"])


In [ ]:
model2.fit(x_train, y_train, epochs= 5 )

Epoch 1/5
33/33 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.8805
Epoch 2/5
33/33 [==============================] - 0s 3ms/step - loss: 0.1655 - accuracy: 0.9728
Epoch 3/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0518 - accuracy: 0.9922
Epoch 4/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0220 - accuracy: 0.9990
Epoch 5/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0110 - accuracy: 1.0000


In [ ]:
model2.get_weights()

[array([[-0.15452233, -0.09858037,  0.12358098, -0.15179051, -0.32168397,
         -0.1495254 ,  0.2725117 , -0.31812468, -0.15853754, -0.08749018,
         -0.18867722, -0.343042  , -0.10224966, -0.22035961,  0.1725807 ,
          0.1258597 , -0.08170858, -0.34493455,  0.21275052,  0.27647457,
          0.09257778,  0.27520946, -0.01243842, -0.26509252,  0.32431316,
          0.06032959, -0.2146415 , -0.26030418,  0.25280228,  0.14442846,
          0.05959453,  0.30424935, -0.3399995 , -0.31040975, -0.24616094,
         -0.2473118 , -0.2646596 ,  0.13082421, -0.32288688, -0.29801446,
         -0.0174451 , -0.35844144, -0.06472534, -0.20135689, -0.04583557,
          0.09139863,  0.05465901,  0.12317076, -0.00586949,  0.32805854,
         -0.33395234, -0.1999331 , -0.05486051,  0.21957774,  0.11285818,
          0.23876718,  0.24996549,  0.27114362, -0.22623949, -0.06786527,
         -0.11076999, -0.09361295,  0.30381235, -0.32719907],
        [-0.30866492, -0.02653553, -0.05485287, -0

In [ ]:
model3 = Sequential()
model3.add(Input(shape=(4,)))
model3.add(Dense(64,activation='relu'))
model3.add(Dropout(rate = 0.2))
model3.add(Dense(32,  activation='relu'))
model3.add(Dropout(rate = 0.2 ))
model3.add(Dense(16,  activation='relu'))
model3.add(Dropout(rate = 0.2 ))
model3.add(Dense(8,  activation='relu'))
model3.add(Dropout(rate = 0.2 ))
model3.add(Dense(1,activation='sigmoid'))

In [ ]:
model3.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 64)                320       
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
_________________________________________________________________
dense_11 (Dense)             (None, 32)                2080      
_________________________________________________________________
dropout_1 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_12 (Dense)             (None, 16)                528       
_________________________________________________________________
dropout_2 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_13 (Dense)             (None, 8)                

In [ ]:
ann_viz(model3, title = "ANN")

In [ ]:
model3.compile(optimizer="adam",
              loss= "binary_crossentropy",
              metrics=["accuracy"])


In [ ]:
model3.fit(x_train, y_train, epochs= 5 )

Epoch 1/5
33/33 [==============================] - 1s 4ms/step - loss: 0.6674 - accuracy: 0.6045
Epoch 2/5
33/33 [==============================] - 0s 4ms/step - loss: 0.5215 - accuracy: 0.7716
Epoch 3/5
33/33 [==============================] - 0s 4ms/step - loss: 0.4190 - accuracy: 0.8610
Epoch 4/5
33/33 [==============================] - 0s 4ms/step - loss: 0.3329 - accuracy: 0.9203
Epoch 5/5
33/33 [==============================] - 0s 4ms/step - loss: 0.2455 - accuracy: 0.9485


In [ ]:
model3.fit(x_train, y_train, epochs= 5 )

Epoch 1/5
33/33 [==============================] - 0s 4ms/step - loss: 0.1729 - accuracy: 0.9660
Epoch 2/5
33/33 [==============================] - 0s 4ms/step - loss: 0.1167 - accuracy: 0.9767
Epoch 3/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0796 - accuracy: 0.9864
Epoch 4/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0700 - accuracy: 0.9806
Epoch 5/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0469 - accuracy: 0.9883


In [ ]:
model3.fit(x_train, y_train, epochs= 5 )

Epoch 1/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0468 - accuracy: 0.9874
Epoch 2/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0371 - accuracy: 0.9913
Epoch 3/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0372 - accuracy: 0.9932
Epoch 4/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0323 - accuracy: 0.9961
Epoch 5/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0266 - accuracy: 0.9961


In [ ]:
model3.fit(x_train, y_train, epochs= 5 )

Epoch 1/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0343 - accuracy: 0.9932
Epoch 2/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0273 - accuracy: 0.9932
Epoch 3/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0217 - accuracy: 0.9932
Epoch 4/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0279 - accuracy: 0.9961
Epoch 5/5
33/33 [==============================] - 0s 4ms/step - loss: 0.0154 - accuracy: 1.0000


In [ ]:
y_predict = model3.predict(x_test)

In [ ]:
y_predict

array([[1.08456999e-09],
       [4.02831165e-06],
       [9.24640517e-07],
       [8.92647874e-15],
       [2.96742575e-10],
       [6.91655089e-09],
       [3.69880127e-10],
       [7.22782612e-10],
       [5.80386006e-09],
       [3.50763030e-10],
       [9.99311328e-01],
       [9.99922276e-01],
       [9.37794464e-09],
       [9.99907255e-01],
       [8.19075510e-08],
       [9.99923348e-01],
       [9.99016643e-01],
       [9.98917222e-01],
       [1.00000000e+00],
       [9.97848392e-01],
       [4.79418623e-11],
       [1.72023773e-09],
       [9.98845816e-01],
       [5.31044687e-11],
       [9.99994516e-01],
       [6.01346584e-10],
       [4.07960341e-12],
       [9.99927759e-01],
       [2.41846592e-14],
       [7.57040969e-13],
       [9.99989629e-01],
       [9.00580588e-09],
       [2.01884617e-07],
       [9.99999404e-01],
       [9.99986768e-01],
       [1.63870462e-11],
       [9.99170661e-01],
       [9.98819888e-01],
       [9.99898911e-01],
       [2.16327822e-09],


In [ ]:
y_predict.shape

(343, 1)

In [ ]:
y_test

430     0
588     0
296     0
184     0
244     0
       ..
1121    1
940     1
1189    1
438     0
1022    1
Name: class, Length: 343, dtype: int64

In [ ]:
y_predict.shape

(343, 1)

In [ ]:
y_class = (y_predict>0.5).astype(int)

In [ ]:
y_class

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [ ]:
y_class = y_class.flatten()

In [ ]:
y_class

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix (y_test, y_class)

array([[191,   0],
       [  0, 152]])

In [ ]:
y_pred = model1.predict(x_test)
y_pred = y_pred.flatten()
y_class = (y_pred>0.5).astype(int)

In [ ]:
confusion_matrix (y_test, y_class)

array([[191,   0],
       [  0, 152]])

In [ ]:
model01 = Sequential()
model01.add(Dense(256, input_shape = (4,), activation='relu'))

model01.add(Dense(1,activation='sigmoid'))

model01.compile(optimizer="adam",
              loss= "binary_crossentropy",
              metrics=["accuracy"])
model01.fit(x_train, y_train, epochs= 2)

Epoch 1/2
33/33 [==============================] - 1s 3ms/step - loss: 0.4236 - accuracy: 0.8144
Epoch 2/2
33/33 [==============================] - 0s 4ms/step - loss: 0.1772 - accuracy: 0.9757


In [ ]:
y_pred1 = model01.predict(x_test)
y_pred1 = y_pred1.flatten()
y_class1 = (y_pred1>0.5).astype(int)
confusion_matrix (y_test, y_class1)

array([[191,   0],
       [  5, 147]])